# Generated by Django 4.2.7 on 2023-11-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_studentcourses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourses',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentcourses',
            old_name='student_id',
            new_name='student',
        ),
    ]
