# Generated by Django 4.2.7 on 2023-11-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_rename_course_id_studentcourses_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='student',
        ),
    ]
