# Generated by Django 4.2.7 on 2023-11-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_remove_studentcourses_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourses',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.student'),
        ),
    ]
