# Generated by Django 4.2.7 on 2023-11-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_studentcourses_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_in', models.DateTimeField()),
                ('signed_out', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.student')),
            ],
        ),
    ]
